#ifndef _VERSION_HEADER_FILE_
	#define _VERSION_HEADER_FILE_

// Version
#define _MARCO_STRING(x) #x
#define MARCO_STRING(x ) _MARCO_STRING( x )

#define MY_VERSION_PART_1			0
#define MY_VERSION_PART_2			0
#define MY_VERSION_PART_3			0
#define MY_VERSION_PART_4			1


#define MY_VERSION_NUMBER			MAKE_VERSION( MY_VERSION_PART_1 , MY_VERSION_PART_2 , MY_VERSION_PART_3 , MY_VERSION_PART_4 )
#define MY_VERSION_DOT_STRING		MARCO_STRING(MY_VERSION_PART_1.MY_VERSION_PART_2.MY_VERSION_PART_3.MY_VERSION_PART_4)

#define MY_VERSION_COMMA_STRING		MY_VERSION_PART_1,MY_VERSION_PART_2,MY_VERSION_PART_3,MY_VERSION_PART_4

#ifdef _WIN64
	#define MY_VERSION_INTERNALNAME	"ci_test.exe\0"
#else
	#define MY_VERSION_INTERNALNAME	"ci_test.exe\0"
#endif // #ifdef _WIN64

#define MY_VERSION_COMMENTS			"ci_test\0"

#define MY_VERSION_COMPANYNAME		"Tiny Studio\0"

#define MY_VERSION_FILEDESCRIPTION	"ci_test\0"

#define MY_VERSION_LEGALCOPYRIGHT	"(C) Tiny Studio All Rights Reserved\0"
#define MY_VERSION_LEGALTRADEMARKS	"https://github.com/tinysec\0"

#define MY_VERSION_PRODUCTNAME		"ci_test\0"

#define MY_VERSION_FILEVERSION		MY_VERSION_DOT_STRING

#define MY_VERSION_ORIGINALFILENAME	MY_VERSION_INTERNALNAME
#define MY_VERSION_PRIVATEBUILD		MY_VERSION_DOT_STRING

#define MY_VERSION_PRODUCTVERSION	MY_VERSION_DOT_STRING
#define MY_VERSION_SPECIALBUILD		MY_VERSION_DOT_STRING


#endif // _VERSION_HEADER_FILE_


